name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "file:./db.sqlite"
  NEXTAUTH_URL: "localhost:3000"
  NEXTAUTH_SECRET: "SECRET"
  WS_URL: "ws://localhost:3001"

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.26.0

      - name: Install Dependencies
        run: pnpm install && pnpm run postinstall

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.26.0

      - name: Install Dependencies
        run: pnpm install && pnpm run postinstall

      - name: Install Chromium
        run: pnpm playwright install chromium

      - name: Build and test
        run: pnpm prebuild && pnpm build && pnpm test-start && pnpm test-dev

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test results
          path: |
            playwright/test-results

      # - name: Print Environment Variable
      #   run: echo $MY_ENV_VAR
