name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      # - name: Print Environment Variable
      #   run: echo $MY_ENV_VAR
